# Generated by Django 4.2.5 on 2023-10-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.IntegerField(null=True)),
            ],
        ),
    ]
